server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/quant_symbols/ {
        proxy_pass http://quant_symbols.quant.mayberry.farm:8089/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/quant_daily_bars/ {
        proxy_pass http://quant_daily_bars.quant.mayberry.farm:8090/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/quant_positions/ {
        proxy_pass http://quant_positions.quant.mayberry.farm:8015/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/quant_signals/ {
        proxy_pass http://quant_signals.quant.mayberry.farm:8016/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
